name: Build TactileBrowser

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  desktop-build-universal:
    name: Build for MacOS (Universal)
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build for MacOS (Universal)
        run: python3 scripts/build_macos.py

  pocketmage-build:
    name: Build for PocketMage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build PocketMage app
        run: python3 scripts/build_pocketmage.py

  tactility-build:
    name: Build for Tactility
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build Tactility app
        run: python3 scripts/build_tactility.py
  
  wasm-build:
    name: Build for WASM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build WASM app
        run: python3 scripts/build_wasm.py
